import sys
import os

# Add project root to PYTHONPATH
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, PROJECT_ROOT)
from Phase_2.zero_shot_visual_agent import ZeroShotVisualVeracityAgent
from PIL import Image

# Initialize agent
agent = ZeroShotVisualVeracityAgent()

# Test with your Gemini image (AI-generated, should detect as fake)
print("\n" + "="*80)
print("Testing with Gemini AI-generated image...")
print("="*80)

image = Image.open("Gemini_Generated_Image_1jzljk1jzljk1jzl.png").convert('RGB')
result = agent.analyze_from_image(image)

print(f"\n📊 RESULT:")
print(f"   Verdict: {result.verdict.upper()}")
print(f"   Authenticity Score: {result.score:.3f}")
print(f"   Confidence: {result.confidence:.3f}")
print(f"   \n   Reasoning: {result.reasoning}")
print(f"\n   Evidence:")
for evidence in result.evidence:
    print(f"      • {evidence}")

print("\n" + "="*80)
print("Expected: FAKE (since it's AI-generated by Gemini)")
print("="*80 + "\n")
